config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do # создает семь следующих маршрутов
  # GET '/posts' => 'posts#index' 	отображает список всех постов
  # GET '/posts/new' => 'posts#new' возвращает форму HTML для создания нового поста
  # POST '/posts' => 'posts#create' 	создает новый пост
  # GET '/posts/:id' => 'posts#show' 	отображает определенный пост
  # GET '/posts/:id/edit' => 'posts#edit' 	возвращает форму HTML для редактирования поста
  # PATCH/PUT '/posts/:id' => 'posts#update' 	обновляет определенный пост
  # DELETE '/posts/:id' => 'posts#destroy' 	удаляет определенный пост
    member do
      get "like", to: "posts#upvote" # 'posts/[id]/like' => "posts#upvote"
      get "dislike", to: "posts#downvote"
    end
    resources :comments
  end
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  belongs_to :user
  has_attached_file :image, styles: { medium: "700x350#", small: "350x250>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.create(params[:comment].permit(:content))
    @comment.user_id = current_user.id
    @comment.post_id = @post.id

    if @comment.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, except: [:index, :show] # Методы Devise

  def index
    @posts = Post.all.order('created_at DESC') # Записи отсортированы по времени создания
  end

  def show
    @comments = Comment.where("post_id = ?", @post)
  end

  def new
    @post = current_user.posts.build # Построение для конкретного пользователя Devise
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to(@post)
    else
      render('new')
    end
  end

  def edit

  end

  def update
    if @post.update(post_params)
      redirect_to(@post)
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to '/'
  end

  def upvote
    @post.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @post.downvote_from current_user
    redirect_to :back
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :link, :description, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Accordions</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
  </head>

  <body>
    <header>
      <div class="wrapper">
        <div class="clearfix">
          <div id="logo"><%= link_to(t('accordeons'), root_path) %></div>
          <nav>
            <% if user_signed_in? %>
                <%= link_to(current_user.email, edit_user_registration_path) %>
                <%= link_to(t('create_new_post'), new_post_path, class: "button") %>
                <%= link_to(t('logout'), destroy_user_session_path, method: :delete) %>
            <% else %>
                <%= link_to(t('devise.sessions.new.sign_in'), new_user_session_path) %>
                <%= link_to(t('devise.registrations.new.sign_up'), new_user_registration_path, class: "button") %>
            <% end %>
          </nav>
        </div>
      </div>
    </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="wrapper"> <%= yield %> </div>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="new_post">
  <%= form_for :post, url: '/posts' do |f| %>
      <div class="headline_post"> <%= t('update_your_post') %> </div>
      <%= t('image') %><br><br> <%= f.file_field(:image) %><br><br>
      <%= t('title') %> <br><%= f.text_field(:title) %><br>
      <%= t('link') %> <br><%= f.text_field(:link) %><br>
      <%= t('description') %><br> <%= f.text_field(:description) %><br>
      <%= f.submit(t('update')) %>
  <% end %>
</div>

app/views/posts/index.html.erb
<p id="intro" xmlns="http://www.w3.org/1999/html">
  <% if user_signed_in? %>
    <%= t('hello') %>
    <%= current_user.email %>
    <br>
  <% end %>
  <span><%= t('share_smth_interesting') %></span>
</p>
<div id = "posts">
  <% @posts.each do |post| %>
      <div class="post">
        <div class="post_image">
          <%= link_to(image_tag(post.image.url(:small)), post) %>
        </div>
        <div class="post_content">
          <div class="title"><h2><%= link_to(post.title, post) %></h2></div>
          <div class="data">
            <div class="clearfix">
              <p class="buttons">
                <span>
                  <i class="fa fa-comments-o">  <%= t('comments') %><%= post.comments.count %></i>
                </span>
                <span>
                  <i class="fa fa-sort">  <%= t('karma') %><%= post.get_likes.size - post.get_dislikes.size %></i>
                </span>
              </p>
            </div>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="new_post">
  <%= form_for :post, url: '/posts' do |f| %>
      <div class="headline_post"><%= t('create_new_post') %> </div>
      <%= t('image') %><br><br> <%= f.file_field(:image) %><br><br>
      <%= t('title') %> <br><%= f.text_field(:title) %><br>
      <%= t('link') %><br> <%= f.text_field(:link) %><br>
      <%= t('description') %> <br><%= f.text_field(:description) %><br>
      <%= f.submit(t('create')) %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div id="post_show">
  <h1><%= @post.title %></h1>
  <div class="username">
    <%= t('shared_by') %>
    <%= @post.user.email %>
    <%= time_ago_in_words(@post.created_at) %>
    <%= t('ago') %>
  </div>
  <div class="clearfix">
    <div class="post_image_description">
      <%= image_tag(@post.image.url(:medium)) %>
      <div class="description"><%= @post.description %></div>
    </div>
    <div class="post_data">
      <%= link_to(t('link'), @post.link, class: 'button') %>
      <%= link_to(like_post_path(@post), method: :get, class: "dataup") do %>
          <i class="fa fa-sort-up"></i>
          <%= t('likes') %><%= @post.get_upvotes.size %>
      <% end %>
      <%= link_to(dislike_post_path(@post), method: :get, class: "datadown") do %>
          <i class="fa fa-sort-down"></i>
          <%= t('dislikes') %><%= @post.get_downvotes.size %>
      <% end %>
      <p class="data">
        <i class="fa fa-comments-o"></i>
        <%= t('comments') %><%= @post.comments.count %>
      </p>
      <% if @post.user == current_user %>
          <%= link_to(t('edit'), edit_post_path(@post), class: "data") %>
          <%= link_to(t('delete'), post_path(@post), method: :delete, data: { confirm: t('sure') }, class: "data") %>
    <% end %>
    </div>
  </div>
</div>
<div id="comments">
  <h2 class="comment_count"><%= t('comments') %><%= @post.comments.count %></h2>
  <% @comments.each do |comment| %>
      <div class="comment">
        <p class="username"><%= comment.user.email %></p>
        <p class="content"><%= comment.content %></p>
      </div>
  <% end %>
  <%= form_for [@post, @post.comments.build] do |f| %>
      <%= f.text_field(:content) %>
      <%= f.submit(t('write_comment'), class: 'button') %>
  <% end %>
</div>